# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates


version: 2
updates:

# Maintain dependencies for npm
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    allow:
      # Allow both direct and indirect updates for all packages in npm ecosystem
      - dependency-type: "all"
    # Only check dependencies security at this test branch
    target-branch: "dependencies_updates"
    commit-message:
      # Prefix all commit messages with "npm-update"
      prefix: "npm-update"
    reviewers:
      - "dluman"
      - "Mai1902"
      
      
